name: Create Communication Server Docker

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: true
  push:
    branches:
      - "main"
    paths:
      - "Dockers_source_code/communication_server/**/*"

defaults:
  run:
    working-directory: ./Dockers_source_code/communication_server

jobs:
  build_new_communication_server_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockers_source_code/communication_server/Dockerfile
          context: ./Dockers_source_code/communication_server/
          push: true
          tags: anandanlk/federation_server_endpoint_test:latest
          platforms: linux/amd64,linux/arm64
